[env]
TERM = "alacritty"

[window]
padding = {x = 4, y = 8}
dynamic_padding = true
opacity = 0.85
blur = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
italic = { style = "Regular" }
size = 16

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
