[general]
import = [
    "./themes/themes/kanagawa_dragon.toml",
]

[env]
TERM = "alacritty"

[window]
padding = {x = 5, y = 5}
dynamic_padding = true
opacity = 1
blur = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
# italic = { style = "RegularItalic" }
size = 16

[cursor]
style = { shape = "Block", blinking = "On"}
blink_timeout = 0
blink_interval = 500

[mouse]
hide_when_typing = true

[colors]
primary = { background = "#222222", foreground = "#c6b7a0" }
selection = { text = "CellForeground", background = "#353535" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
