[general]
import = [ "./themes/kanagawa_dragon.toml" ]

[env]
TERM = "alacritty"

[window]
padding = {x = 5, y = 5}
dynamic_padding = true
opacity = 1
blur = true
decorations = "Buttonless"

[font]
normal = { family = "CommitMono Nerd Font" }
size = 14
offset = { x = 0, y = 3 }

[cursor]
style = { shape = "Underline", blinking = "Off"}

[mouse]
hide_when_typing = true

[colors]
selection = { text = "CellForeground", background = "#151515" }
cursor = { text = "#000000", cursor = "CellForeground" }
