[general]
import = [
    "./themes/themes/kanagawa_dragon.toml",
]

[env]
TERM = "alacritty"

[window]
padding = {x = 0, y = 0}
dynamic_padding = true
opacity = 1
blur = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
italic = { style = "Regular" }
size = 16

[cursor]
style = { shape = "Block", blinking = "On"}
blink_timeout = 0
blink_interval = 500

[mouse]
hide_when_typing = true

[colors]
primary = {background = "#222222"}
selection = { text = "CellForeground", background = "#353535" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
