[env]
# TERM = "xterm-256color"

[window]
padding = {x = 4, y = 8}
dynamic_padding = true
opacity = 0.85
blur = true

decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Thin" }
italic = { style = "Light" }
size = 16
