[general]
import = [
    "themes/themes/kanagawa_dragon.toml",
]

[env]
TERM = "alacritty"

[window]
padding = {x = 4, y = 8}
dynamic_padding = true
opacity = 0.85
blur = true
decorations = "Buttonless"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Light" }
italic = { style = "Regular" }
size = 16

[cursor]
style = { shape = "Block", blinking = "On"}
blink_timeout = 0
blink_interval = 500

[mouse]
hide_when_typing = true

[colors]
selection = { text = "CellForeground", background = "#353535" }
