format = """
$username$hostname \
$directory\
$git_branch$git_status$git_commit$git_metrics$git_state \
$python\
$line_break\
$character
"""

[username]
style_user = 'purple'
# style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true
# aliases = { "corpuser034g" = "matchai" }

[hostname]
style = 'purple'
format = '[$ssh_symbol$hostname]($style)'
ssh_only = true
aliases = {"Max-Macbook-Pro" = "macbook"}

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[\\$](bright-black)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[](bright-black)"

[git_branch]
format = "([$branch ]($style))"
style = "fg:8"

[git_metrics]
disabled = false

[git_status]
style = "purple"
# format = '[\[$all_status$ahead_behind\]]($style)'
stashed = "≡"
use_git_executable = true

[git_state]
format = '[\($state $progress_current\$progress_total\)]($style)'
style = "bright-black"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"
