format = """
$username$hostname \
$directory\
$git_branch$git_state$git_status \
$python \
$line_break\
$character
"""

[username]
style_user = 'purple'
# style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true
# aliases = { "corpuser034g" = "matchai" }

[hostname]
style = 'purple'
format = '[$ssh_symbol$hostname]($style)'
ssh_only = true
aliases = {"Max-Macbook-Pro" = "home"}

[directory]
style = "blue"
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
style = "purple"
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)]($ahead_behind$stashed)]($style)"
format = '([$all_status$ahead_behind]($style) )'
# conflicted = ""
# untracked = ""
modified = "*"
# staged = ""
# renamed = ""
# deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"
