after-login-command = []

# after-startup-command = [
#     'exec-and-forget sketchybar --reload',
#     'exec-and-forget borders',
# ]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 10
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
# on-focused-changed = ['move-mouse window-lazy-center']

# Notify Sketchybar about workspace change
# exec-on-workspace-change = ['/bin/bash', '-c',
#     'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE'
# ]

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical   = 5
outer.top        = 0
outer.bottom     = -1
outer.left       = 0
outer.right      = 0

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

cmd-shift-h = ['join-with left',  'mode main']
cmd-shift-j = ['join-with down',  'mode main']
cmd-shift-k = ['join-with up',    'mode main']
cmd-shift-l = ['join-with right', 'mode main']

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-shift-f     = 'fullscreen'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
# alt-5 = 'workspace 5'
# alt-6 = 'workspace 6'
# alt-7 = 'workspace 7'
# alt-8 = 'workspace 8'
# alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
# alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
# alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
# alt-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
# alt-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
# alt-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'
[mode.service.binding]
esc       = ['reload-config',                 'mode main']
r         = ['flatten-workspace-tree',        'mode main'] # reset layout
f         = ['layout floating tiling',        'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# ---------------------------------------------------------------------------------

[[on-window-detected]]
if.app-id = 'com.cycling74.Max'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.preview'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.FontBook'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.yourcompany.SoulseekQt'
run       = ['layout floating']

# [[on-window-detected]]
# if.app-id = 'net.kovidgoyal.kitty'
# run       = ['move-node-to-workspace T']

[[on-window-detected]]
if.app-id = 'com.nordvpn.macos'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.m0k.transmission'
run       = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.codeweavers.CrossOver'
run       = ['layout floating']
